version: '3.7'
services:
  app:
    image: app
    build:
      context: .
    container_name: app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dms
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/dms_mongo
      - MONGO_DB=dms_mongo
    ports:
      - 8080:8080
    depends_on:
      - db
      - mongodb
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_DB=dms_mongo