version: '3.7'
services:
  app:
    image: app
    build:
      context: .
    container_name: app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=dms
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/dms_mongo
      - MONGO_DB=dms_mongo
      - LOGS_FOLDER=/usr/share/logs
    ports:
      - 8080:8080
    volumes:
      - /home/user/logs:/usr/share/logs
    depends_on:
      - db
      - mongodb
    networks:
      - elk
  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dms
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - elk
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_DB=dms_mongo
    networks:
      - elk
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.13.4
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.13.4
    volumes:
      - /home/user/logs:/usr/share/logstash/input
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.13.4
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
