feign:
  client:
    url: https://www.cbr-xml-daily.ru/daily_json.js

spring:
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: database
      database: ${MONGO_DB:dms_mongo}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dms}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    name: ${POSTGRES_DB:dms}
  main:
    allow-bean-definition-overriding: true

app:
  cache-timeout: 300000

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
        web:
          TRACE

jwt:
  header: Authorization
  secret: secret
  expiration: 604800
