feign:
  client:
    url: https://www.cbr-xml-daily.ru/daily_json.js

spring:
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}
      authentication-database: database
      database: ${MONGO_DB:dms_mongo}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:dms}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    name: ${POSTGRES_DB:dms}
  main:
    allow-bean-definition-overriding: true

  mvc:
    log-request-details: off

app:
  cache-timeout: 300000

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
#        web:
#          TRACE
    org.zalando.logbook: TRACE
  file:
    name: ${LOGS_FOLDER:/home/user/logs}/elk-stack.log
#    name: /home/user/logs/elk-stack.log

jwt:
  header: Authorization
  secret: secret
  expiration: 604800

logbook:
  include:
    - /api/**
    - /actuator/**
  exclude:
    - /actuator/health
    - /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
      - token
    parameters:
      - token
      - password
      - client_secret
  write:
    chunk-size: 1000
